---
name: Labo 2.0
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp
      - name: Run ESLint
        run: yarn lint
        working-directory: ./webapp
