---
name: Labo 2.0

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository code
        uses: actions/checkout@v3
      - name: Inloggen indockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./Dockerfile
          tags: gregoirelacombe/webapp:latest
          push: true
      - name: dependencies installeren
        run: yarn install
        working-directory: ./webapp
      - name: lint uitvoeren
        run: yarn eslint . --fix
        working-directory: ./webapp
